apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: "gpu-mnist-inferenceservice"
spec:
  predictor:
    serviceAccountName: kserve-local-s3
    model:
      modelFormat:
        name: tensorflow
      protocolVersion: v2
      storageUri: ""
      resources:
        limits:
          nvidia.com/gpu: 1