apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: gpu-mnist-inferenceservice
spec:
  predictor:
    serviceAccountName: kserve-local-s3
    tensorflow:
      protocolVersion: v2
      storageUri: s3://mlflow.rag-cluster01/<experiment_id>/<run_id>/artifacts/model
      resources:
        limits:
          nvidia.com/gpu: 1
