apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: "expname"
  namespace: user-namespace 
spec:
  predictor:
    serviceAccountName: kserve-local-s3
    sklearn:
      protocolVersion: "v2"
      storageUri: "s3://mlflow.{s3-bucket}/exp-id/models/model-id/artifacts"
